spring.application.name=CRM_Project

# ===== DATABASE =====
spring.datasource.url=jdbc:mysql://localhost:3306/db_crm
spring.datasource.username=root
spring.datasource.password=

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (optional) fix l?i timezone
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh